_wandb:
    value:
        cli_version: 0.24.2
        e:
            c21nr86uc4w3brcb0hnpw1p2apbmnkob:
                args:
                    - --dataset_base_path
                    - ../../../DL3DV-10K_960P/1K
                    - --dataset_metadata_path
                    - ../../../DL3DV-10K_960P/1K
                    - --height
                    - "192"
                    - --width
                    - "336"
                    - --num_frames
                    - "7"
                    - --dataset_repeat
                    - "1"
                    - --model_id_with_origin_paths
                    - Wan-AI/Wan2.1-I2V-14B-480P:diffusion_pytorch_model*.safetensors,Wan-AI/Wan2.1-I2V-14B-480P:models_t5_umt5-xxl-enc-bf16.pth,Wan-AI/Wan2.1-I2V-14B-480P:Wan2.1_VAE.pth,Wan-AI/Wan2.1-I2V-14B-480P:models_clip_open-clip-xlm-roberta-large-vit-huge-14.pth
                    - --learning_rate
                    - "1e-4"
                    - --num_epochs
                    - "80"
                    - --remove_prefix_in_ckpt
                    - pipe.dit.
                    - --output_path
                    - ./models/train/Wan2.1-SE-14B-lora32-6to1_random
                    - --lora_base_model
                    - dit
                    - --lora_target_modules
                    - q,k,v,o,ffn.0,ffn.2
                    - --lora_rank
                    - "32"
                    - --extra_inputs
                    - input_image
                    - --modify_channels
                    - --new_in_dim
                    - "420"
                    - --gradient_accumulation_steps
                    - "1"
                    - --initialize_model_on_cpu
                    - --seperated_encoding
                    - --wandb_project
                    - wan-se-14b
                    - --wandb_run_name
                    - lora32-6to1_random
                codePath: examples/wanvideo/model_training/train_SE.py
                codePathLocal: model_training/train_SE.py
                cpu_count: 48
                cpu_count_logical: 96
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "205349208064"
                        used: "96237154304"
                email: szqwu57@gmail.com
                executable: /home/qiwu2/anaconda3/envs/wan2/bin/python3.11
                git:
                    commit: 6f5371442d01c7a196700c35c5d7e125b65171a9
                    remote: git@github.com:szqwu/DiffSynth-Studio.git
                gpu: NVIDIA RTX 6000 Ada Generation
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-57af34aa-a463-7b1b-efc2-6272d833d9c7
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-f596dd05-8ac2-f51c-65b0-ac6ef2b9521d
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-298a4eba-7866-2640-8309-30480a4e17d5
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-08e26e78-ce6c-71a2-d2fe-202f634ba063
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-5c5721ae-aa77-122a-61cd-99fa09095e8f
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-4fbc2df2-f2e1-e4cb-7598-3274b3e96b59
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-0c52d29d-5d69-4ba1-5470-12a68ae54d24
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-1f938115-7e10-7676-199e-268f3c2e64d6
                host: trinity-1-38
                memory:
                    total: "1081957167104"
                os: Linux-4.18.0-372.32.1.el8_6.x86_64-x86_64-with-glibc2.28
                program: /data2/qiwu2/DiffSynth-Studio/examples/wanvideo/model_training/train_SE.py
                python: CPython 3.11.14
                root: /data2/qiwu2/DiffSynth-Studio/examples/wanvideo
                startedAt: "2026-02-10T21:51:17.702226Z"
                writerId: c21nr86uc4w3brcb0hnpw1p2apbmnkob
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 98
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
                - 98
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.11.14
            "5": 0.24.2
            "6": 5.1.0
            "12": 0.24.2
            "13": linux-x86_64
audio_processor_path:
    value: null
data_file_keys:
    value: image,video
dataset_base_path:
    value: ../../../DL3DV-10K_960P/1K
dataset_metadata_path:
    value: ../../../DL3DV-10K_960P/1K
dataset_num_workers:
    value: 0
dataset_repeat:
    value: 1
extra_inputs:
    value: input_image
find_unused_parameters:
    value: false
fp8_models:
    value: null
fuse_vae_embedding_in_latents_multiple:
    value: false
gradient_accumulation_steps:
    value: 1
height:
    value: 192
initialize_model_on_cpu:
    value: true
learning_rate:
    value: 0.0001
lora_base_model:
    value: dit
lora_checkpoint:
    value: null
lora_rank:
    value: 32
lora_target_modules:
    value: q,k,v,o,ffn.0,ffn.2
max_pixels:
    value: 1048576
max_timestep_boundary:
    value: 1
min_timestep_boundary:
    value: 0
model_id_with_origin_paths:
    value: Wan-AI/Wan2.1-I2V-14B-480P:diffusion_pytorch_model*.safetensors,Wan-AI/Wan2.1-I2V-14B-480P:models_t5_umt5-xxl-enc-bf16.pth,Wan-AI/Wan2.1-I2V-14B-480P:Wan2.1_VAE.pth,Wan-AI/Wan2.1-I2V-14B-480P:models_clip_open-clip-xlm-roberta-large-vit-huge-14.pth
model_paths:
    value: null
modify_channels:
    value: true
new_in_dim:
    value: 420
num_epochs:
    value: 80
num_frames:
    value: 7
offload_models:
    value: null
output_path:
    value: ./models/train/Wan2.1-SE-14B-lora32-6to1_random
preset_lora_model:
    value: null
preset_lora_path:
    value: null
remove_prefix_in_ckpt:
    value: pipe.dit.
save_steps:
    value: null
seperated_encoding:
    value: true
task:
    value: sft
tokenizer_path:
    value: null
trainable_models:
    value: null
use_gradient_checkpointing:
    value: false
use_gradient_checkpointing_offload:
    value: false
wandb_project:
    value: wan-se-14b
wandb_run_name:
    value: lora32-6to1_random
weight_decay:
    value: 0.01
width:
    value: 336
